roberto:
  # Publish all joint states -----------------------------------
  joint_state_controller:
    type: joint_state_controller/JointStateController
    publish_rate: 50  

  servo_joint_position_controller:
    type: roberto_control/RobertoPositionController
    joints:
      front_right_servo_controller:
        joint: servo_front_right
        pid: {p: 1.0,  i: 0.001, d: 0.0, i_clamp: 10.0}
      front_left_servo_controller:
        joint: servo_front_left
        pid: {p: 1.0,  i: 0.001, d: 0.0, i_clamp: 10.0}

  motor_joint_velocity_controller:
    type: roberto_control/RobertoVelocityController
    joints:
      front_left_controller:
        joint: front_left_wheel_hinge
        pid: {p: 10.0,  i: 0.1, d: 0.0}
      front_right_controller:
        joint: front_right_wheel_hinge
        pid: {p: 10.0,  i: 0.1, d: 0.0}
      rear_left_controller:
        joint: rear_left_wheel_hinge
        pid: {p: 10.0,  i: 0.1, d: 0.0}
      rear_right_controller:
        joint: rear_right_wheel_hinge
        pid: {p: 10.0,  i: 0.1, d: 0.0}