<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro">

	<xacro:include filename="$(find roberto_models_kinetic)/models/inertia_tensors.xacro"/>

	<xacro:macro name="RobertoPlatformTop" params="name parent mesh_collis:=^|simplified mesh_visual:=^|detailed model_dir:=^">

		<xacro:property name="ParentLink2ThisLink"> <!--parent link to this joint tf-->
			<origin xyz="0 0 ${spacerLength+spacerPosZ-platformTopHeight-0.001}" rpy="0 0 0"/> 
	    </xacro:property>

	    <xacro:property name="ThisLink2Inert"> <!--this link 2 inertial center tf, mass data-->
			<box_inertial x="${platformTopWidth}" y="${platformTopLength}"  z="${platformTopHeight}" mass="${platformTopMass}" /> 
	    </xacro:property>

	    <xacro:property name="ThisLink2STL"> <!--this link 2 mesh center tf, file-->
			<origin xyz="${platformTopWidth/2} -${platformTopLength/2} 0" rpy="0 ${pi} 0"/> 
			<geometry> <mesh filename="file://${model_dir}/meshes/platform_top.dae"/> </geometry> 
			<!--<material name="light_blue"/> -->
	    </xacro:property>

	    <xacro:property name="ThisLink2XML"> <!--this link 2 simple mesh center tf, file-->
			<origin xyz="0 0 0" rpy="0 ${pi} 0"/> 
			<geometry> <box size="${platformTopWidth} ${platformTopLength} ${platformTopHeight}" /> </geometry> 
			<!--<material name="light_blue"/> -->
	    </xacro:property>
	        
	    <!-- choosing the appropriate collision and visual mesh -->
	    <xacro:property name="ThisVisual"> <box size="0.0001 0.0001 0.0001" /> </xacro:property><!--no mesh-->
	    <xacro:property name="ThisCollis"> <box size="0.0001 0.0001 0.0001" /> </xacro:property><!--no mesh-->
	    <xacro:if value="${mesh_visual ==   'detailed'}"> <xacro:property name="ThisVisual">  <xacro:insert_block name="ThisLink2STL"/> </xacro:property> </xacro:if><!--detailed stl mesh-->
	    <xacro:if value="${mesh_collis ==   'detailed'}"> <xacro:property name="ThisCollis">  <xacro:insert_block name="ThisLink2STL"/> </xacro:property> </xacro:if><!--detailed stl mesh-->
	    <xacro:if value="${mesh_visual == 'simplified'}"> <xacro:property name="ThisVisual">  <xacro:insert_block name="ThisLink2XML"/> </xacro:property> </xacro:if><!--minimalist mesh-->
	    <xacro:if value="${mesh_collis == 'simplified'}"> <xacro:property name="ThisCollis">  <xacro:insert_block name="ThisLink2XML"/> </xacro:property> </xacro:if><!--minimalist mesh-->
	    
	    
	    <!-- joint and link definition -->    
	    <joint name="${parent}2${name}_joint" type="fixed">
			<parent link="${parent}_link"/>
			<child  link="${name}_link" />
			<xacro:insert_block name="ParentLink2ThisLink" />
	    </joint>		

	    <link name="${name}_link">    
			<xacro:insert_block name="ThisLink2Inert"/>
			<visual>    <xacro:insert_block name="ThisVisual"/> </visual>
			<collision> <xacro:insert_block name="ThisCollis"/> </collision>
	    </link>
	    
	    
	    <gazebo reference="${name}_link"> 
			<!--<material>Gazebo/LightBlueLaser</material> -->
	    </gazebo>
		

	</xacro:macro>
</robot>